apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com-personal:masiur-rahaman/argocd-spike.git
    targetRevision: HEAD
    path: charts/my-app
    helm:
      valueFiles:
        - values/dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
