apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:masiur-rahaman/argocd-spike.git
    targetRevision: HEAD
    path: charts/my-app
    helm:
      valueFiles:
        - values/staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
#    automated:
#      prune: true
#      selfHeal: true
